# Generated by Django 5.2.5 on 2025-08-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0014_city_alter_attraction_city'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
