# Generated by Django 5.2.5 on 2025-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction_routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='routeattraction',
            name='order',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
