# Generated by Django 5.2.5 on 2025-08-18 11:57

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='meeting_address',
            field=models.CharField(default='Адрес не указан', max_length=255),
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_email',
            field=models.EmailField(default='Email для связи не указан', max_length=254),
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU'),
        ),
    ]
