# Generated by Django 5.2.5 on 2025-08-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
    ]
