# Generated by Django 5.2.5 on 2025-08-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_tour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
    ]
