# Generated by Django 5.2.5 on 2025-08-28 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tours.tour'),
        ),
    ]
