# Generated by Django 5.2.5 on 2025-08-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
