# Generated by Django 5.2.5 on 2025-08-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_attraction_description_attraction_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='average_rating',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
