# Generated by Django 5.2.5 on 2025-08-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_attraction_average_rating_attraction_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='admin_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attraction',
            name='need_photo',
            field=models.BooleanField(default=False),
        ),
    ]
