# Generated by Django 5.2.5 on 2025-08-16 15:04

import attractions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_attraction_admin_reviewed_attraction_need_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='image_url',
        ),
        migrations.AddField(
            model_name='attraction',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=attractions.models.main_photo_path),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='need_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AttractionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=attractions.models.additional_photos_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='attractions.attraction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
