# Generated by Django 5.2.5 on 2025-08-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_remove_attraction_image_url_attraction_main_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='admin_uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_photos/'),
        ),
    ]
