# Generated by Django 5.2.5 on 2025-08-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_attraction_admin_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
