# Generated by Django 5.2.5 on 2025-08-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0007_attraction_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='opening_hours',
            field=models.CharField(blank=True, help_text="Время работы, например, '10:00-18:00'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='reviews_url',
            field=models.URLField(blank=True, help_text='Ссылка на отзывы', null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='website_url',
            field=models.URLField(blank=True, help_text='Ссылка на сайт или отзывы', null=True),
        ),
    ]
