# Generated by Django 5.2.5 on 2025-08-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0008_attraction_address_attraction_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='address',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='email',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='reviews_url',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='website_url',
        ),
    ]
