# Generated by Django 5.2.5 on 2025-08-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0010_attraction_address_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
