# Generated by Django 5.2.5 on 2025-08-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0012_city_alter_attraction_city'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
