# Generated by Django 5.2.5 on 2025-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0014_city_alter_attraction_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
