# Generated by Django 5.2.5 on 2025-08-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0015_alter_attraction_city_delete_city'),
        ('cities', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attractions', to='cities.city'),
        ),
    ]
