# Generated by Django 5.2.5 on 2025-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0016_alter_attraction_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='admin_uploaded_image',
        ),
        migrations.AddField(
            model_name='attraction',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='average_check',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='house',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(),
        ),
    ]
