# Generated by Django 5.2.5 on 2025-08-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0017_remove_attraction_admin_uploaded_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
