# Generated by Django 5.2.5 on 2025-08-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0020_alter_attraction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
