# Generated by Django 5.2.5 on 2025-08-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0022_pendingattractionupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description_short',
            field=models.TextField(blank=True, null=True),
        ),
    ]
