# Generated by Django 5.2.5 on 2025-08-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0025_attraction_description_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='description_short',
        ),
    ]
