# Generated by Django 5.2.5 on 2025-08-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0026_remove_attraction_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description_short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
