# Generated by Django 5.2.5 on 2025-08-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0028_pendingattractionupdate_description_short'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attraction',
            table='attractions_attraction',
        ),
    ]
