# Generated by Django 5.2.5 on 2025-08-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0029_alter_attraction_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attraction',
            table=None,
        ),
    ]
