# Generated by Django 5.2.5 on 2025-08-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0030_alter_attraction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingattractionupdate',
            name='description_short',
            field=models.TextField(blank=True, null=True),
        ),
    ]
