# Generated by Django 5.2.5 on 2025-08-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0031_alter_attraction_description_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description_short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendingattractionupdate',
            name='description_short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
