# Generated by Django 5.2.5 on 2025-08-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0032_alter_attraction_description_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
