# Generated by Django 5.2.5 on 2025-08-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0033_alter_attraction_latitude_alter_attraction_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
