# Generated by Django 5.2.5 on 2025-08-28 11:37

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0034_alter_attraction_latitude_alter_attraction_longitude'),
        ('cities', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attraction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='attraction_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='pendingattractionupdate',
            index=models.Index(fields=['status'], name='pending_update_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingattractionupdate',
            index=models.Index(fields=['attraction', 'status'], name='pua_status_idx'),
        ),
    ]
