# Generated by Django 5.2.5 on 2025-08-28 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0035_attraction_attraction_name_trgm_and_more'),
        ('cities', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pendingattractionupdate',
            name='pua_status_idx',
        ),
        migrations.AddIndex(
            model_name='pendingattractionupdate',
            index=models.Index(fields=['status', 'name'], name='pua_status_idx'),
        ),
    ]
